export const PLAYERS = [

  // =====================================================
  // STANDARD — 40
  // =====================================================

  {
    id: "std_gk_01",
    name: "David Marshall",
    nationality: "Scotland",
    position: "GK",
    era: "2006-2010",
    rarity: "Standard",
    overall: 66,
    awareness: 72,
    catching: 70,
    reflexes: 76,
    diving: 73,
    jumping: 74,
    physical: 78,
  },

  {
    id: "std_gk_02",
    name: "Tim Krul",
    nationality: "Netherlands",
    position: "GK",
    era: "2011-2015",
    rarity: "Standard",
    overall: 67,
    awareness: 75,
    catching: 73,
    reflexes: 81,
    diving: 78,
    jumping: 76,
    physical: 76,
  },

  {
    id: "std_gk_03",
    name: "Steve Mandanda",
    nationality: "France",
    position: "GK",
    era: "2006-2010",
    rarity: "Standard",
    overall: 68,
    awareness: 79,
    catching: 77,
    reflexes: 82,
    diving: 80,
    jumping: 78,
    physical: 80,
  },

  {
    id: "std_gk_04",
    name: "Rui Patricio",
    nationality: "Portugal",
    position: "GK",
    era: "2011-2015",
    rarity: "Standard",
    overall: 69,
    awareness: 82,
    catching: 80,
    reflexes: 84,
    diving: 83,
    jumping: 81,
    physical: 82,
  },

  {
    id: "std_df_01",
    name: "Bacary Sagna",
    nationality: "France",
    position: "RB",
    era: "2006-2010",
    rarity: "Standard",
    overall: 68,
    pace: 78,
    shooting: 35,
    passing: 72,
    dribbling: 64,
    defending: 82,
    physical: 84,
  },

  {
    id: "std_df_02",
    name: "Glen Johnson",
    nationality: "England",
    position: "RB",
    era: "2006-2010",
    rarity: "Standard",
    overall: 66,
    pace: 84,
    shooting: 45,
    passing: 68,
    dribbling: 73,
    defending: 67,
    physical: 78,
  },

  {
    id: "std_df_03",
    name: "Stephen Warnock",
    nationality: "England",
    position: "LB",
    era: "2006-2010",
    rarity: "Standard",
    overall: 63,
    pace: 74,
    shooting: 30,
    passing: 66,
    dribbling: 58,
    defending: 73,
    physical: 75,
  },

  {
    id: "std_df_04",
    name: "John Arne Riise",
    nationality: "Norway",
    position: "LB",
    era: "2001-2005",
    rarity: "Standard",
    overall: 69,
    pace: 82,
    shooting: 78,
    passing: 76,
    dribbling: 66,
    defending: 78,
    physical: 88,
  },

  {
    id: "std_df_05",
    name: "Alex",
    nationality: "Brazil",
    position: "CB",
    era: "2006-2010",
    rarity: "Standard",
    overall: 67,
    pace: 64,
    shooting: 39,
    passing: 63,
    dribbling: 42,
    defending: 82,
    physical: 91,
  },

  {
    id: "std_df_06",
    name: "Martin Demichelis",
    nationality: "Argentina",
    position: "CB",
    era: "2006-2010",
    rarity: "Standard",
    overall: 68,
    pace: 55,
    shooting: 32,
    passing: 68,
    dribbling: 43,
    defending: 83,
    physical: 84,
  },

  {
    id: "std_df_07",
    name: "Per Mertesacker",
    nationality: "Germany",
    position: "CB",
    era: "2011-2015",
    rarity: "Standard",
    overall: 69,
    pace: 42,
    shooting: 25,
    passing: 67,
    dribbling: 35,
    defending: 86,
    physical: 91,
  },

  {
    id: "std_df_08",
    name: "Gary Cahill",
    nationality: "England",
    position: "CB",
    era: "2011-2015",
    rarity: "Standard",
    overall: 68,
    pace: 63,
    shooting: 38,
    passing: 62,
    dribbling: 40,
    defending: 84,
    physical: 88,
  },

  {
    id: "std_df_09",
    name: "Nicolas Otamendi",
    nationality: "Argentina",
    position: "CB",
    era: "2011-2015",
    rarity: "Standard",
    overall: 69,
    pace: 68,
    shooting: 36,
    passing: 65,
    dribbling: 42,
    defending: 86,
    physical: 90,
  },

  {
    id: "std_df_10",
    name: "Kolo Toure",
    nationality: "Ivory Coast",
    position: "CB",
    era: "2006-2010",
    rarity: "Standard",
    overall: 69,
    pace: 76,
    shooting: 32,
    passing: 65,
    dribbling: 43,
    defending: 85,
    physical: 91,
  },

  {
    id: "std_mf_01",
    name: "Michael Carrick",
    nationality: "England",
    position: "CDM",
    era: "2006-2010",
    rarity: "Standard",
    overall: 69,
    pace: 58,
    shooting: 45,
    passing: 86,
    dribbling: 64,
    defending: 73,
    physical: 68,
  },

  {
    id: "std_mf_02",
    name: "Mikel Arteta",
    nationality: "Spain",
    position: "CM",
    era: "2006-2010",
    rarity: "Standard",
    overall: 67,
    pace: 61,
    shooting: 53,
    passing: 82,
    dribbling: 72,
    defending: 58,
    physical: 65,
  },

  {
    id: "std_mf_03",
    name: "Sami Khedira",
    nationality: "Germany",
    position: "CM",
    era: "2011-2015",
    rarity: "Standard",
    overall: 69,
    pace: 68,
    shooting: 65,
    passing: 76,
    dribbling: 60,
    defending: 78,
    physical: 89,
  },

  {
    id: "std_mf_04",
    name: "Marouane Fellaini",
    nationality: "Belgium",
    position: "CM",
    era: "2011-2015",
    rarity: "Standard",
    overall: 68,
    pace: 53,
    shooting: 67,
    passing: 68,
    dribbling: 55,
    defending: 74,
    physical: 94,
  },

  {
    id: "std_mf_05",
    name: "Javi Martinez",
    nationality: "Spain",
    position: "CDM",
    era: "2011-2015",
    rarity: "Standard",
    overall: 69,
    pace: 61,
    shooting: 42,
    passing: 76,
    dribbling: 55,
    defending: 84,
    physical: 88,
  },

  {
    id: "std_mf_06",
    name: "James Milner",
    nationality: "England",
    position: "CM",
    era: "2006-2010",
    rarity: "Standard",
    overall: 69,
    pace: 76,
    shooting: 59,
    passing: 79,
    dribbling: 68,
    defending: 74,
    physical: 84,
  },

  {
    id: "std_mf_07",
    name: "Nigel de Jong",
    nationality: "Netherlands",
    position: "CDM",
    era: "2006-2010",
    rarity: "Standard",
    overall: 68,
    pace: 58,
    shooting: 35,
    passing: 68,
    dribbling: 48,
    defending: 87,
    physical: 90,
  },

  {
    id: "std_mf_08",
    name: "Ramires",
    nationality: "Brazil",
    position: "CM",
    era: "2011-2015",
    rarity: "Standard",
    overall: 68,
    pace: 88,
    shooting: 58,
    passing: 71,
    dribbling: 74,
    defending: 72,
    physical: 82,
  },

  {
    id: "std_wg_01",
    name: "Antonio Valencia",
    nationality: "Ecuador",
    position: "RW",
    era: "2006-2010",
    rarity: "Standard",
    overall: 69,
    pace: 90,
    shooting: 66,
    passing: 78,
    dribbling: 79,
    defending: 47,
    physical: 82,
  },

  {
    id: "std_wg_02",
    name: "Nani",
    nationality: "Portugal",
    position: "LW",
    era: "2006-2010",
    rarity: "Standard",
    overall: 69,
    pace: 88,
    shooting: 74,
    passing: 77,
    dribbling: 86,
    defending: 32,
    physical: 67,
  },

  {
    id: "std_wg_03",
    name: "Victor Moses",
    nationality: "Nigeria",
    position: "RW",
    era: "2011-2015",
    rarity: "Standard",
    overall: 66,
    pace: 88,
    shooting: 58,
    passing: 63,
    dribbling: 79,
    defending: 38,
    physical: 82,
  },

  {
    id: "std_wg_04",
    name: "Adnan Januzaj",
    nationality: "Belgium",
    position: "LW",
    era: "2011-2015",
    rarity: "Standard",
    overall: 64,
    pace: 78,
    shooting: 48,
    passing: 72,
    dribbling: 80,
    defending: 28,
    physical: 61,
  },

  {
    id: "std_wg_05",
    name: "Jesus Navas",
    nationality: "Spain",
    position: "RW",
    era: "2011-2015",
    rarity: "Standard",
    overall: 69,
    pace: 91,
    shooting: 57,
    passing: 83,
    dribbling: 85,
    defending: 40,
    physical: 60,
  },

  {
    id: "std_wg_06",
    name: "Ashley Young",
    nationality: "England",
    position: "LW",
    era: "2006-2010",
    rarity: "Standard",
    overall: 69,
    pace: 86,
    shooting: 65,
    passing: 80,
    dribbling: 81,
    defending: 44,
    physical: 69,
  },

  {
    id: "std_st_01",
    name: "Jermain Defoe",
    nationality: "England",
    position: "ST",
    era: "2006-2010",
    rarity: "Standard",
    overall: 69,
    pace: 88,
    shooting: 84,
    passing: 62,
    dribbling: 79,
    defending: 25,
    physical: 65,
  },

  {
    id: "std_st_02",
    name: "Peter Crouch",
    nationality: "England",
    position: "ST",
    era: "2006-2010",
    rarity: "Standard",
    overall: 66,
    pace: 42,
    shooting: 76,
    passing: 63,
    dribbling: 54,
    defending: 22,
    physical: 88,
  },

  {
    id: "std_st_03",
    name: "Emmanuel Adebayor",
    nationality: "Togo",
    position: "ST",
    era: "2006-2010",
    rarity: "Standard",
    overall: 69,
    pace: 76,
    shooting: 81,
    passing: 64,
    dribbling: 68,
    defending: 23,
    physical: 88,
  },

  {
    id: "std_st_04",
    name: "Mario Gomez",
    nationality: "Germany",
    position: "ST",
    era: "2006-2010",
    rarity: "Standard",
    overall: 69,
    pace: 69,
    shooting: 88,
    passing: 53,
    dribbling: 63,
    defending: 20,
    physical: 87,
  },

  {
    id: "std_st_05",
    name: "Kevin Gameiro",
    nationality: "France",
    position: "ST",
    era: "2011-2015",
    rarity: "Standard",
    overall: 68,
    pace: 87,
    shooting: 80,
    passing: 55,
    dribbling: 74,
    defending: 18,
    physical: 63,
  },

  {
    id: "std_st_06",
    name: "Alexandre Lacazette",
    nationality: "France",
    position: "ST",
    era: "2011-2015",
    rarity: "Standard",
    overall: 69,
    pace: 82,
    shooting: 84,
    passing: 66,
    dribbling: 80,
    defending: 20,
    physical: 75,
  },

  {
    id: "std_extra_01",
    name: "Victor Lindelof",
    nationality: "Sweden",
    position: "CB",
    era: "2016-2020",
    rarity: "Standard",
    overall: 66,
    pace: 61,
    shooting: 25,
    passing: 72,
    dribbling: 40,
    defending: 75,
    physical: 73,
  },

  {
    id: "std_extra_02",
    name: "Eric Bailly",
    nationality: "Ivory Coast",
    position: "CB",
    era: "2016-2020",
    rarity: "Standard",
    overall: 67,
    pace: 75,
    shooting: 27,
    passing: 54,
    dribbling: 37,
    defending: 78,
    physical: 86,
  },

  {
    id: "std_extra_03",
    name: "Danny Rose",
    nationality: "England",
    position: "LB",
    era: "2016-2020",
    rarity: "Standard",
    overall: 67,
    pace: 82,
    shooting: 38,
    passing: 70,
    dribbling: 67,
    defending: 70,
    physical: 78,
  },

  {
    id: "std_extra_04",
    name: "Danny Drinkwater",
    nationality: "England",
    position: "CM",
    era: "2016-2020",
    rarity: "Standard",
    overall: 63,
    pace: 52,
    shooting: 42,
    passing: 76,
    dribbling: 58,
    defending: 57,
    physical: 69,
  },

  {
    id: "std_extra_05",
    name: "Theo Walcott",
    nationality: "England",
    position: "RW",
    era: "2006-2010",
    rarity: "Standard",
    overall: 68,
    pace: 95,
    shooting: 68,
    passing: 61,
    dribbling: 78,
    defending: 24,
    physical: 60,
  },

  {
    id: "std_extra_06",
    name: "Wilfried Bony",
    nationality: "Ivory Coast",
    position: "ST",
    era: "2011-2015",
    rarity: "Standard",
    overall: 66,
    pace: 64,
    shooting: 78,
    passing: 54,
    dribbling: 57,
    defending: 18,
    physical: 89,
  },

  // =====================================================
  // RARE — 30
  // =====================================================

  {
    id: "rare_gk_01",
    name: "Edwin van der Sar",
    nationality: "Netherlands",
    position: "GK",
    era: "2006-2010",
    rarity: "Rare",
    overall: 82,
    awareness: 91,
    catching: 91,
    reflexes: 89,
    diving: 88,
    jumping: 85,
    physical: 83,
  },

  {
    id: "rare_gk_02",
    name: "Petr Cech",
    nationality: "Czech Republic",
    position: "GK",
    era: "2006-2010",
    rarity: "Rare",
    overall: 83,
    awareness: 92,
    catching: 94,
    reflexes: 91,
    diving: 90,
    jumping: 87,
    physical: 85,
  },

  {
    id: "rare_gk_03",
    name: "Oliver Kahn",
    nationality: "Germany",
    position: "GK",
    era: "2001-2005",
    rarity: "Rare",
    overall: 84,
    awareness: 94,
    catching: 95,
    reflexes: 94,
    diving: 91,
    jumping: 89,
    physical: 92,
  },

  {
    id: "rare_df_01",
    name: "Rio Ferdinand",
    nationality: "England",
    position: "CB",
    era: "2006-2010",
    rarity: "Rare",
    overall: 83,
    pace: 79,
    shooting: 30,
    passing: 82,
    dribbling: 57,
    defending: 91,
    physical: 83,
  },

  {
    id: "rare_df_02",
    name: "Pepe",
    nationality: "Portugal",
    position: "CB",
    era: "2006-2010",
    rarity: "Rare",
    overall: 82,
    pace: 78,
    shooting: 32,
    passing: 61,
    dribbling: 40,
    defending: 91,
    physical: 94,
  },

  {
    id: "rare_df_03",
    name: "Vincent Kompany",
    nationality: "Belgium",
    position: "CB",
    era: "2011-2015",
    rarity: "Rare",
    overall: 83,
    pace: 73,
    shooting: 42,
    passing: 72,
    dribbling: 45,
    defending: 93,
    physical: 94,
  },

  {
    id: "rare_df_04",
    name: "Javier Zanetti",
    nationality: "Argentina",
    position: "RB",
    era: "2001-2005",
    rarity: "Rare",
    overall: 82,
    pace: 84,
    shooting: 42,
    passing: 82,
    dribbling: 76,
    defending: 88,
    physical: 86,
  },

  {
    id: "rare_df_05",
    name: "Ashley Cole",
    nationality: "England",
    position: "LB",
    era: "2006-2010",
    rarity: "Rare",
    overall: 84,
    pace: 88,
    shooting: 38,
    passing: 81,
    dribbling: 77,
    defending: 94,
    physical: 84,
  },

  {
    id: "rare_df_06",
    name: "Patrice Evra",
    nationality: "France",
    position: "LB",
    era: "2006-2010",
    rarity: "Rare",
    overall: 81,
    pace: 86,
    shooting: 33,
    passing: 75,
    dribbling: 72,
    defending: 87,
    physical: 86,
  },

  {
    id: "rare_df_07",
    name: "Paulo Ferreira",
    nationality: "Portugal",
    position: "RB",
    era: "2001-2005",
    rarity: "Rare",
    overall: 78,
    pace: 79,
    shooting: 30,
    passing: 74,
    dribbling: 65,
    defending: 88,
    physical: 79,
  },

  {
    id: "rare_df_08",
    name: "Gerard Pique",
    nationality: "Spain",
    position: "CB",
    era: "2011-2015",
    rarity: "Rare",
    overall: 84,
    pace: 62,
    shooting: 46,
    passing: 88,
    dribbling: 63,
    defending: 90,
    physical: 85,
  },

  {
    id: "rare_mf_01",
    name: "Frank Lampard",
    nationality: "England",
    position: "CM",
    era: "2006-2010",
    rarity: "Rare",
    overall: 84,
    pace: 73,
    shooting: 91,
    passing: 89,
    dribbling: 78,
    defending: 63,
    physical: 82,
  },

  {
    id: "rare_mf_02",
    name: "Steven Gerrard",
    nationality: "England",
    position: "CM",
    era: "2001-2005",
    rarity: "Rare",
    overall: 84,
    pace: 78,
    shooting: 88,
    passing: 92,
    dribbling: 82,
    defending: 73,
    physical: 88,
  },

  {
    id: "rare_mf_03",
    name: "Andrea Pirlo",
    nationality: "Italy",
    position: "CDM",
    era: "2006-2010",
    rarity: "Rare",
    overall: 84,
    pace: 62,
    shooting: 76,
    passing: 97,
    dribbling: 88,
    defending: 58,
    physical: 61,
  },

  {
    id: "rare_mf_04",
    name: "David Beckham",
    nationality: "England",
    position: "RM",
    era: "2001-2005",
    rarity: "Rare",
    overall: 82,
    pace: 82,
    shooting: 88,
    passing: 95,
    dribbling: 83,
    defending: 62,
    physical: 74,
  },

  {
    id: "rare_mf_05",
    name: "Wesley Sneijder",
    nationality: "Netherlands",
    position: "CAM",
    era: "2006-2010",
    rarity: "Rare",
    overall: 83,
    pace: 78,
    shooting: 86,
    passing: 94,
    dribbling: 88,
    defending: 42,
    physical: 66,
  },

  {
    id: "rare_mf_06",
    name: "Cesc Fabregas",
    nationality: "Spain",
    position: "CM",
    era: "2006-2010",
    rarity: "Rare",
    overall: 83,
    pace: 67,
    shooting: 74,
    passing: 96,
    dribbling: 85,
    defending: 45,
    physical: 64,
  },

  {
    id: "rare_mf_07",
    name: "David Silva",
    nationality: "Spain",
    position: "CAM",
    era: "2011-2015",
    rarity: "Rare",
    overall: 84,
    pace: 78,
    shooting: 76,
    passing: 94,
    dribbling: 95,
    defending: 38,
    physical: 59,
  },

  {
    id: "rare_mf_08",
    name: "Ivan Rakitic",
    nationality: "Croatia",
    position: "CM",
    era: "2011-2015",
    rarity: "Rare",
    overall: 81,
    pace: 67,
    shooting: 78,
    passing: 91,
    dribbling: 79,
    defending: 68,
    physical: 76,
  },

  {
    id: "rare_wg_01",
    name: "Arjen Robben",
    nationality: "Netherlands",
    position: "RW",
    era: "2006-2010",
    rarity: "Rare",
    overall: 84,
    pace: 95,
    shooting: 91,
    passing: 84,
    dribbling: 95,
    defending: 28,
    physical: 67,
  },

  {
    id: "rare_wg_02",
    name: "Angel Di Maria",
    nationality: "Argentina",
    position: "RW",
    era: "2011-2015",
    rarity: "Rare",
    overall: 83,
    pace: 90,
    shooting: 80,
    passing: 91,
    dribbling: 92,
    defending: 42,
    physical: 70,
  },

  {
    id: "rare_wg_03",
    name: "Gareth Bale",
    nationality: "Wales",
    position: "RW",
    era: "2016-2020",
    rarity: "Rare",
    overall: 84,
    pace: 96,
    shooting: 91,
    passing: 82,
    dribbling: 90,
    defending: 35,
    physical: 87,
  },

  {
    id: "rare_wg_04",
    name: "Franck Ribery",
    nationality: "France",
    position: "LW",
    era: "2006-2010",
    rarity: "Rare",
    overall: 84,
    pace: 91,
    shooting: 83,
    passing: 89,
    dribbling: 94,
    defending: 29,
    physical: 72,
  },

  {
    id: "rare_st_01",
    name: "Samuel Eto'o",
    nationality: "Cameroon",
    position: "ST",
    era: "2006-2010",
    rarity: "Rare",
    overall: 84,
    pace: 94,
    shooting: 92,
    passing: 71,
    dribbling: 88,
    defending: 22,
    physical: 79,
  },

  {
    id: "rare_st_02",
    name: "Didier Drogba",
    nationality: "Ivory Coast",
    position: "ST",
    era: "2006-2010",
    rarity: "Rare",
    overall: 84,
    pace: 76,
    shooting: 94,
    passing: 75,
    dribbling: 78,
    defending: 24,
    physical: 96,
  },

  {
    id: "rare_st_03",
    name: "Robin van Persie",
    nationality: "Netherlands",
    position: "ST",
    era: "2011-2015",
    rarity: "Rare",
    overall: 83,
    pace: 78,
    shooting: 95,
    passing: 84,
    dribbling: 91,
    defending: 18,
    physical: 73,
  },

  {
    id: "rare_st_04",
    name: "Edinson Cavani",
    nationality: "Uruguay",
    position: "ST",
    era: "2011-2015",
    rarity: "Rare",
    overall: 82,
    pace: 83,
    shooting: 91,
    passing: 68,
    dribbling: 76,
    defending: 27,
    physical: 89,
  },

  {
    id: "rare_st_05",
    name: "Zlatan Ibrahimovic",
    nationality: "Sweden",
    position: "ST",
    era: "2011-2015",
    rarity: "Rare",
    overall: 84,
    pace: 74,
    shooting: 96,
    passing: 88,
    dribbling: 89,
    defending: 22,
    physical: 95,
  },

  {
    id: "rare_st_06",
    name: "Karim Benzema",
    nationality: "France",
    position: "ST",
    era: "2016-2020",
    rarity: "Rare",
    overall: 84,
    pace: 82,
    shooting: 91,
    passing: 86,
    dribbling: 87,
    defending: 19,
    physical: 82,
  },

  {
    id: "rare_st_07",
    name: "Luis Suarez",
    nationality: "Uruguay",
    position: "ST",
    era: "2011-2015",
    rarity: "Rare",
    overall: 84,
    pace: 84,
    shooting: 96,
    passing: 85,
    dribbling: 93,
    defending: 30,
    physical: 83,
  },

  // =====================================================
  // EPIC — 20
  // =====================================================

  {
    id: "epic_gk_01",
    name: "Manuel Neuer",
    nationality: "Germany",
    position: "GK",
    era: "2011-2015",
    rarity: "Epic",
    overall: 91,
    awareness: 96,
    catching: 91,
    reflexes: 94,
    diving: 92,
    jumping: 91,
    physical: 91,
  },

  {
    id: "epic_gk_03",
    name: "Iker Casillas",
    nationality: "Spain",
    position: "GK",
    era: "2006-2010",
    rarity: "Epic",
    overall: 88,
    awareness: 94,
    catching: 91,
    reflexes: 98,
    diving: 96,
    jumping: 88,
    physical: 79,
  },

  {
    id: "epic_gk_02",
    name: "Alisson Becker",
    nationality: "Brazil",
    position: "GK",
    era: "2016-2020",
    rarity: "Epic",
    overall: 90,
    awareness: 94,
    catching: 93,
    reflexes: 95,
    diving: 94,
    jumping: 91,
    physical: 90,
  },

  {
    id: "epic_df_01",
    name: "Sergio Ramos",
    nationality: "Spain",
    position: "CB",
    era: "2006-2010",
    rarity: "Epic",
    overall: 90,
    pace: 82,
    shooting: 71,
    passing: 83,
    dribbling: 68,
    defending: 94,
    physical: 91,
  },

  {
    id: "epic_df_02",
    name: "Virgil van Dijk",
    nationality: "Netherlands",
    position: "CB",
    era: "2016-2020",
    rarity: "Epic",
    overall: 91,
    pace: 82,
    shooting: 35,
    passing: 87,
    dribbling: 61,
    defending: 98,
    physical: 96,
  },

  {
    id: "epic_df_03",
    name: "Giorgio Chiellini",
    nationality: "Italy",
    position: "CB",
    era: "2011-2015",
    rarity: "Epic",
    overall: 88,
    pace: 68,
    shooting: 28,
    passing: 68,
    dribbling: 42,
    defending: 96,
    physical: 94,
  },

  {
    id: "epic_df_04",
    name: "Philipp Lahm",
    nationality: "Germany",
    position: "RB",
    era: "2006-2010",
    rarity: "Epic",
    overall: 89,
    pace: 88,
    shooting: 38,
    passing: 91,
    dribbling: 88,
    defending: 94,
    physical: 76,
  },

  {
    id: "epic_df_05",
    name: "Dani Alves",
    nationality: "Brazil",
    position: "RB",
    era: "2011-2015",
    rarity: "Epic",
    overall: 90,
    pace: 88,
    shooting: 60,
    passing: 92,
    dribbling: 91,
    defending: 80,
    physical: 78,
  },

  {
    id: "epic_mf_01",
    name: "Xavi",
    nationality: "Spain",
    position: "CM",
    era: "2006-2010",
    rarity: "Epic",
    overall: 91,
    pace: 76,
    shooting: 76,
    passing: 99,
    dribbling: 94,
    defending: 64,
    physical: 67,
  },

  {
    id: "epic_mf_02",
    name: "Andres Iniesta",
    nationality: "Spain",
    position: "CM",
    era: "2011-2015",
    rarity: "Epic",
    overall: 92,
    pace: 79,
    shooting: 82,
    passing: 98,
    dribbling: 98,
    defending: 47,
    physical: 66,
  },

  {
    id: "epic_mf_03",
    name: "Luka Modric",
    nationality: "Croatia",
    position: "CM",
    era: "2016-2020",
    rarity: "Epic",
    overall: 91,
    pace: 79,
    shooting: 78,
    passing: 97,
    dribbling: 94,
    defending: 68,
    physical: 73,
  },

  {
    id: "epic_mf_04",
    name: "Toni Kroos",
    nationality: "Germany",
    position: "CM",
    era: "2011-2015",
    rarity: "Epic",
    overall: 90,
    pace: 78,
    shooting: 84,
    passing: 97,
    dribbling: 84,
    defending: 72,
    physical: 70,
  },

  {
    id: "epic_mf_05",
    name: "Kevin De Bruyne",
    nationality: "Belgium",
    position: "CAM",
    era: "2016-2020",
    rarity: "Epic",
    overall: 91,
    pace: 84,
    shooting: 91,
    passing: 96,
    dribbling: 91,
    defending: 59,
    physical: 79,
  },

  {
    id: "epic_mf_06",
    name: "N'Golo Kante",
    nationality: "France",
    position: "CDM",
    era: "2016-2020",
    rarity: "Epic",
    overall: 89,
    pace: 84,
    shooting: 64,
    passing: 84,
    dribbling: 82,
    defending: 95,
    physical: 91,
  },

  {
    id: "epic_mf_07",
    name: "Sergio Busquets",
    nationality: "Spain",
    position: "CDM",
    era: "2011-2015",
    rarity: "Epic",
    overall: 88,
    pace: 55,
    shooting: 45,
    passing: 94,
    dribbling: 84,
    defending: 91,
    physical: 72,
  },

  {
    id: "epic_mf_08",
    name: "Patrick Vieira",
    nationality: "France",
    position: "CM",
    era: "2001-2005",
    rarity: "Epic",
    overall: 90,
    pace: 81,
    shooting: 69,
    passing: 89,
    dribbling: 78,
    defending: 94,
    physical: 96,
  },

  {
    id: "epic_wg_01",
    name: "Mohamed Salah",
    nationality: "Egypt",
    position: "RW",
    era: "2016-2020",
    rarity: "Epic",
    overall: 90,
    pace: 93,
    shooting: 91,
    passing: 84,
    dribbling: 94,
    defending: 38,
    physical: 76,
  },

  {
    id: "epic_wg_02",
    name: "Neymar Jr",
    nationality: "Brazil",
    position: "LW",
    era: "2016-2020",
    rarity: "Epic",
    overall: 92,
    pace: 91,
    shooting: 91,
    passing: 94,
    dribbling: 99,
    defending: 35,
    physical: 62,
  },

  {
    id: "epic_st_01",
    name: "Robert Lewandowski",
    nationality: "Poland",
    position: "ST",
    era: "2016-2020",
    rarity: "Epic",
    overall: 91,
    pace: 79,
    shooting: 97,
    passing: 84,
    dribbling: 91,
    defending: 25,
    physical: 90,
  },

  {
    id: "epic_st_02",
    name: "Erling Haaland",
    nationality: "Norway",
    position: "ST",
    era: "2021-now",
    rarity: "Epic",
    overall: 90,
    pace: 91,
    shooting: 96,
    passing: 68,
    dribbling: 86,
    defending: 18,
    physical: 97,
  },

  // =====================================================
  // LEGENDARY — 10
  // =====================================================

  {
    id: "legend_gk_01",
    name: "Gianluigi Buffon",
    nationality: "Italy",
    position: "GK",
    era: "2000-2005",
    rarity: "Legendary",
    overall: 94,
    awareness: 98,
    catching: 97,
    reflexes: 96,
    diving: 94,
    jumping: 91,
    physical: 94,
  },

  {
    id: "legend_df_01",
    name: "Paolo Maldini",
    nationality: "Italy",
    position: "CB",
    era: "2000-2005",
    rarity: "Legendary",
    overall: 95,
    pace: 84,
    shooting: 42,
    passing: 91,
    dribbling: 82,
    defending: 99,
    physical: 91,
  },

  {
    id: "legend_df_02",
    name: "Alessandro Nesta",
    nationality: "Italy",
    position: "CB",
    era: "2000-2005",
    rarity: "Legendary",
    overall: 94,
    pace: 76,
    shooting: 27,
    passing: 84,
    dribbling: 67,
    defending: 99,
    physical: 91,
  },

  {
    id: "legend_df_03",
    name: "Fabio Cannavaro",
    nationality: "Italy",
    position: "CB",
    era: "2006-2010",
    rarity: "Legendary",
    overall: 94,
    pace: 86,
    shooting: 30,
    passing: 78,
    dribbling: 74,
    defending: 99,
    physical: 91,
  },

  {
    id: "legend_mf_01",
    name: "Zinedine Zidane",
    nationality: "France",
    position: "CAM",
    era: "2000-2005",
    rarity: "Legendary",
    overall: 95,
    pace: 82,
    shooting: 91,
    passing: 97,
    dribbling: 96,
    defending: 46,
    physical: 84,
  },

  {
    id: "legend_wg_01",
    name: "Ronaldinho",
    nationality: "Brazil",
    position: "LW",
    era: "2001-2005",
    rarity: "Legendary",
    overall: 94,
    pace: 91,
    shooting: 92,
    passing: 95,
    dribbling: 99,
    defending: 32,
    physical: 78,
  },

  {
    id: "legend_wg_02",
    name: "Lionel Messi",
    nationality: "Argentina",
    position: "RW",
    era: "2011-2015",
    rarity: "Legendary",
    overall: 96,
    pace: 90,
    shooting: 96,
    passing: 97,
    dribbling: 99,
    defending: 38,
    physical: 72,
  },

  {
    id: "legend_wg_03",
    name: "Cristiano Ronaldo",
    nationality: "Portugal",
    position: "LW",
    era: "2011-2015",
    rarity: "Legendary",
    overall: 96,
    pace: 95,
    shooting: 97,
    passing: 88,
    dribbling: 94,
    defending: 45,
    physical: 95,
  },

  {
    id: "legend_wg_04",
    name: "Ronaldo Nazario",
    nationality: "Brazil",
    position: "ST",
    era: "2000-2005",
    rarity: "Legendary",
    overall: 95,
    pace: 96,
    shooting: 98,
    passing: 83,
    dribbling: 97,
    defending: 18,
    physical: 91,
  },

  {
    id: "legend_st_01",
    name: "Thierry Henry",
    nationality: "France",
    position: "ST",
    era: "2000-2005",
    rarity: "Legendary",
    overall: 94,
    pace: 96,
    shooting: 94,
    passing: 88,
    dribbling: 94,
    defending: 20,
    physical: 84,
  },

];